import EVEStaticData
import SwiftUI

struct SDEUpdateView: View {
    @Environment(AppEnvironment.self) private var env
    @State private var manifestURLString = ""

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 22) {
                header
                localSection
                remoteSection
                statusSection
            }
            .padding(.horizontal, 20)
            .padding(.bottom, 40)
        }
        .background(Color.eveBackground)
        .navigationTitle("SDE Updates")
        .navigationBarTitleDisplayMode(.inline)
        .task {
            env.sdeUpdates.refreshLocalMetadata()
            manifestURLString = env.sdeUpdates.manifestURLString
        }
        .onChange(of: manifestURLString) { _, newValue in
            env.sdeUpdates.manifestURLString = newValue
        }
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Static Data")
                .font(.system(size: 34, weight: .bold))
                .foregroundStyle(Color.eveText)

            Text("Install a prebuilt Canopus SDE SQLite package generated by Tools/sde-import.")
                .font(.system(size: 14))
                .foregroundStyle(Color.eveTextMuted)
        }
    }

    private var localSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            sectionTitle("LOCAL DATABASE")

            if let metadata = env.sdeUpdates.localMetadata {
                VStack(spacing: 0) {
                    infoRow("Source", metadata.source.rawValue.capitalized)
                    infoRow("Build", metadata.build ?? "Unknown")
                    infoRow("Generated", metadata.generatedAt ?? "Unknown")
                    infoRow("Schema", metadata.schemaVersion ?? "Unknown")
                    infoRow("Size", formattedBytes(metadata.fileSize))
                }
                .evePanel()
            } else {
                Text("No readable SDE database is installed.")
                    .font(.system(size: 14))
                    .foregroundStyle(Color.eveTextMuted)
            }
        }
    }

    private var remoteSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionTitle("REMOTE PACKAGE")

            TextField("https://example.com/canopus-sde-manifest.json", text: $manifestURLString)
                .textInputAutocapitalization(.never)
                .autocorrectionDisabled()
                .keyboardType(.URL)
                .font(.system(size: 14, design: .monospaced))
                .padding(12)
                .foregroundStyle(Color.eveText)
                .background(Color.evePanel.opacity(0.9))
                .clipShape(RoundedRectangle(cornerRadius: 8))

            if let manifest = env.sdeUpdates.remoteManifest {
                VStack(spacing: 0) {
                    infoRow("Latest Build", manifest.build)
                    infoRow("Generated", manifest.generatedAt ?? "Unknown")
                    infoRow("Schema", manifest.schemaVersion)
                    if let byteSize = manifest.byteSize {
                        infoRow("Size", formattedBytes(UInt64(byteSize)))
                    }
                }
                .evePanel()
            }

            HStack(spacing: 12) {
                Button("Check") {
                    Task { await env.sdeUpdates.checkForUpdates() }
                }
                .buttonStyle(.borderedProminent)

                Button("Install") {
                    Task {
                        if await env.sdeUpdates.installUpdate() {
                            await env.reloadRepository()
                        }
                    }
                }
                .buttonStyle(.bordered)
                .disabled(env.sdeUpdates.remoteManifest == nil)
            }
        }
    }

    private var statusSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            sectionTitle("STATUS")

            HStack(spacing: 10) {
                if isBusy {
                    ProgressView()
                        .controlSize(.small)
                }
                Text(statusText)
                    .font(.system(size: 14, weight: .medium))
                    .foregroundStyle(statusColor)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(14)
            .background(Color.evePanel.opacity(0.9))
            .clipShape(RoundedRectangle(cornerRadius: 8))
        }
    }

    private func sectionTitle(_ title: String) -> some View {
        Text(title)
            .font(.system(size: 12, weight: .semibold, design: .monospaced))
            .tracking(4)
            .foregroundStyle(Color.eveTextMuted)
    }

    private func infoRow(_ title: String, _ value: String) -> some View {
        HStack(alignment: .firstTextBaseline) {
            Text(title)
                .foregroundStyle(Color.eveTextMuted)
            Spacer(minLength: 12)
            Text(value)
                .foregroundStyle(Color.eveText)
                .multilineTextAlignment(.trailing)
        }
        .font(.system(size: 15))
        .padding(.vertical, 10)
        .padding(.horizontal, 14)
    }

    private func formattedBytes(_ value: UInt64) -> String {
        ByteCountFormatter.string(fromByteCount: Int64(value), countStyle: .file)
    }

    private var isBusy: Bool {
        switch env.sdeUpdates.phase {
        case .checking, .downloading, .installing:
            true
        default:
            false
        }
    }

    private var statusText: String {
        switch env.sdeUpdates.phase {
        case .idle:
            "Ready."
        case .checking:
            "Checking manifest..."
        case .upToDate:
            "Local SDE is up to date."
        case .updateAvailable:
            "Update available."
        case .downloading:
            "Downloading SDE package..."
        case .installing:
            "Installing SDE package..."
        case .installed:
            "SDE update installed."
        case .failed(let message):
            message
        }
    }

    private var statusColor: Color {
        switch env.sdeUpdates.phase {
        case .failed:
            .red
        case .updateAvailable, .installed:
            .eveCyan
        default:
            .eveText
        }
    }
}

private extension View {
    func evePanel() -> some View {
        self
            .background(Color.evePanel.opacity(0.9))
            .clipShape(RoundedRectangle(cornerRadius: 8))
    }
}
